name: web_socket_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
#  http_server: ^1.0.0
  args: ^2.0.0
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  shelf_web_socket: ^1.0.1
  shelf_static: ^1.1.0
  json_annotation: ^4.3.0
  retrofit_generator: ^3.0.0+1
  json_serializable: ^6.0.1
  mongo_dart: ^0.7.4+1
  build_runner: ^2.1.5
  quiver: ^3.0.1+1
  logging: ^1.0.2

dev_dependencies:
  build_web_compilers: '>=2.16.1 <3.2.2'
  build_runner: '>=2.1.0 <2.1.8'
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
